### PR TITLE
Add achievement checks

### PR DESCRIPTION
**Pull request by Refrac**
This adds the Drink and Consumable achievement checks to UseSlot

### CODE REVIEW

**Comment by Refrac** [comment]
Fixed the itemkit command because the Snowboard id was changed in InternalItem.xml

**Comment by Refrac** [comment]
Added DefeatEnemy and DefeatEnemyInLevel achievement checks

**Comment by Refrac** [comment]
Added Sour Bathog Boogers item

**Comment by Refrac** [comment]
Add CompleteQuest, CompleteQuestInLevel and ExploreTrail achievement checks

**Comment by Refrac** [comment]
Fixed conflicts this should be mergable now

**Review by FeroxFoxxo — APPROVED** [review]
LGTM

**Pull request merged**
